### ISSUE TITLE
CPU/PPU emulation bugs

### ISSUE THREAD

**Issue by asiekierka** [xdanieldzd/StoicGoose#9]
Compare https://asie.pl/files/accutest_20221122.zip real hardware output with emulator output:

*The NEC V30MZ does not ignore the immediate operand in AAD/AAM calls. This is contrary to NEC V20/V30 behaviour, as well as many existing emulators. It is, broadly speaking, important to remember that the V30MZ is much closer to "an 80186-compatible CPU with much better opcode timings" than "a V20/V30 derivative".
* The sprite base location register's access to 0x4000-0x7FFF memory is gated by the color mode bit, not by the 4bpp mode bit.

More information and additional quirks worth checking [here](https://github.com/ares-emulator/ares/pull/878).

**Comment by xdanieldzd** [comment]
Thanks for the report! I should've fixed at least these two issues with commit 475e26dbc4bae0a32f31fc9a036c3ba8e3c3a656, and the respective builds will be [available for testing here](https://github.com/xdanieldzd/StoicGoose/actions/runs/3535479023) in a moment.

I guess the [Sacred Tech Scroll](http://perfectkiosk.net/stsws.html) is the most recent and accurate WonderSwan documentation available, right? If so, I'll be reading through it and look into improving ex. display controller/PPU accuracy based on that soon. Any further test ROMs are still more than welcome, tho!

![Screenshot with fixes](https://user-images.githubusercontent.com/7199225/203641728-19834a2d-d194-4130-beb3-b3eee74dc98f.png)

**Comment by asiekierka** [comment]
Yes. In general, I try to keep track of all publicly available WonderSwan resources [here](https://github.com/WonderfulToolchain/awesome-wsdev).

It is very useful to not think of the V30MZ as at all related to the V20/V30. If you study the V30MZ manual, it has a section dedicated to the differences between V30HL and V30MZ, and they all consistently point at removing V20/V30-specific quirks and trying to match how the 80186 behaved instead - of course, they couldn't say it outright, because NEC got into legal trouble with Intel before... and they probably got some edge cases wrong still.

**Comment by asiekierka** [comment]
There are also some minor bits of information only available in FluBBa's NitroSwan, as he is another party doing independent original research. (He's also working on a CPU behavior test ROM, but with no ETA.)

**Comment by xdanieldzd** [comment]
Not sure if I misread STSWS while writing the code changes in the above commit, but I had to refine my pixel value 0 opacity handling: A value of zero appears to always be transparent in 4bpp mode, while 2bpp mode works as described (i.e. 0 is always opaque with palettes 0 to 3, always transparent with palettes 4 to 7). If 2bpp logic is applied regardless of bit depth, games using 4bpp mode break badly - see commit e8c80cf7b32c2d05af68e028bab3bc40f23bdbf1 for the changes.

If this is something that's not accurately documented yet (and not just reading comprehension failure on my part), could you maybe test the opacity behavior per mode on hardware?

**Comment by asiekierka** [comment]
You are correct, and this is an omission in STSWS and WSMan both. Thank you!
